const { defaults } = require("autoprefixer")

export const MENUS={
    system:"系统",
    userManagement:"用户管理",
    authorityManagement:"权限管理",
    roleManagement:"角色管理",
    organizationManagement:"机构管理",
    menuManagement:"菜单管理",
    dictionaryManagement:"字典管理",
    index:"主页",
    personal:"个人",
    infoManagement:"信息管理",
    leaveApply:"请假申请",
    myAttendence:"我的考勤",
    invoiceApply:"发票申请",
    EHR:"EHR",
    contractManagement:"合同管理",
    companyPolicy:"公司制度",
    leaveManagement:"请假管理",
    attendanceManagement:"考勤管理",
    invoiceManagement:"发票管理",
    message:"消息",
    myMessage:"我的消息",
    notification:"公告管理",
    talent:"人才",
    talentPool:"人才库",
    talentPublic:"公共库",
    allTalent:"所有人才",
    customer:"客户",
    myCustomer:"我的客户",
    customerPublic:"公共库",
    allCustomer:"所有客户",
    project:"项目",
    myProject:"我的项目",
    allProject:"全部项目",
    index:"主页"
}

